### ISSUE TITLE
Get SyntaxError: Unexpected identifier when migrate contract

### ISSUE THREAD

**Issue by Samboy76** [Uniswap/v2-periphery#132]
**Issue**
SyntaxError: Unexpected _identifier_

**Steps to Reproduce**
running truffle migrate in terminal

**Expected Behavior**
migrate successfully

**Actual Results**

===========================
> Compiling @uniswap\v2-core\contracts\interfaces\IUniswapV2Pair.sol
> Compiling @uniswap\v2-periphery\contracts\libraries\SafeMath.sol
> Compiling @uniswap\v2-periphery\contracts\libraries\UniswapV2Library.sol
> Compiling .\contracts\FlashloanArbitrage.sol
> Compiling .\contracts\Migrations.sol
> Compiling .\contracts\interfaces\IERC20.sol
> Compiling .\contracts\interfaces\IUniswapV2Callee.sol
> Compiling .\contracts\interfaces\IUniswapV2Factory.sol
> Compiling .\contracts\interfaces\IUniswapV2Router01.sol
> Compiling .\contracts\interfaces\IUniswapV2Router02.sol
> Artifacts written to C:\Samuel\Blockchain\Flashloan-arbitrage-bot-uniswap-v2\build\contracts
> Compiled successfully using:
   - solc: 0.6.6+commit.6c089d02.Emscripten.clang

2_deploy_contracts.js
=====================

Exiting: Review successful transactions manually by checking the transaction hashes above on Etherscan.

C:\Samuel\Blockchain\Flashloan-arbitrage-bot-uniswap-v2\node_modules\@uniswap\v2-periphery\contracts\libraries\UniswapV2Library.sol:2
pragma solidity >=0.5.0;
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1055:15)
    at Module._compile (node:internal/modules/cjs/loader:1090:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions.<computed> [as .js] (C:\Samuel\Blockchain\Flashloan-arbitrage-bot-uniswap-v2\node_modules\ts-node\src\index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at C:\Samuel\Blockchain\Flashloan-arbitrage-bot-uniswap-v2\migrations\deploy_contracts.ts:12:30
    at Migration._load (webpack:///./packages/migrate/Migration.js:53:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Migration.run (webpack:///./packages/migrate/Migration.js:202:1)
    at async Object.runMigrations (webpack:///./packages/migrate/index.js:142:1)
    at async Object.runFrom (webpack:///./packages/migrate/index.js:107:1)
    at async Object.run (webpack:///./packages/migrate/index.js:91:1)
    at async module.exports (webpack:///./packages/core/lib/commands/migrate/runMigrations.js:10:1)
    at async module.exports (webpack:///./packages/core/lib/commands/migrate/setUpDryRunEnvironmentThenRunMigrations.js:37:1)  
    at async Object.module.exports [as run] (webpack:///./packages/core/lib/commands/migrate/run.js:33:1)
    at async runCommand (webpack:///./packages/core/lib/command-utils.js:201:1)
Truffle v5.5.28 (core: 5.5.28)
Node v16.17.0
PS C:\Samuel\Blockchain\Flashloan-arbitrage-bot-uniswap-v2> truffle version
Truffle v5.5.28 (core: 5.5.28)
Ganache v7.4.0
Solidity - 0.6.6 (solc-js)
Node v16.17.0
Web3.js v1.7.4__

**content of deploy_contracts.ts**
```
type Network = "development" | "kovan" | "mainnet";

module.exports = (artifacts: Truffle.Artifacts) => {
  return async (
    deployer: Truffle.Deployer,
    network: Network,
    accounts: string[]
  ) => {
    const UniswapV2Library = require("@uniswap/v2-periphery/contracts/libraries/UniswapV2Library.sol");
    const FlashloanArbitrage = artifacts.require("FlashloanArbitrage");

    deployer.deploy(UniswapV2Library);
    deployer.link(UniswapV2Library, FlashloanArbitrage);
    deployer.deploy(FlashloanArbitrage,
                    // sushiFactory flashloaner
                    web3.utils.toChecksumAddress("0xC0AEe478e3658e2610c5F7A4A2E1777cE9e4f2Ac"), 
                    // uniswap Router
                    web3.utils.toChecksumAddress("0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D")) 

    const flashloanArbitrage = await FlashloanArbitrage.deployed();
    console.log(
      `FlashloanArbitrage deployed at ${flashloanArbitrage.address} in network: ${network}.`
    );
  }
}
```

**Content of truffle-config.js**

```
compilers: {
    solc: {
      version: "0.6.6",      // Fetch exact version from solc-bin (default: truffle's version)
      "debug": {
        "revertStrings": "default",
        "debugInfo": ["location", "snippet"]
      },
    }
  },
```

Environment
Truffle v5.5.28 (core: 5.5.28)
Ganache v7.4.0
Solidity - 0.6.6 (solc-js)
Node v16.17.0
Web3.js v1.7.4

**Comment by Samboy76** [comment]
Closing issue as n/a
